// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// messaMessagingClientMockgingClient is an autogenerated mock type for the messagingClient type
type MessagingClientMock struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipients, data
func (_m MessagingClientMock) Send(recipients []string, mtype string, data []byte) error {
	ret := _m.Called(recipients, data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, []byte) error); ok {
		r0 = rf(recipients, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
