// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	messaging "github.com/joinself/self-go-sdk/messaging"
	mock "github.com/stretchr/testify/mock"
)

// MessagingServiceMock is an autogenerated mock type for the MessagingServiceMock type
type MessagingServiceMock struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: msgType, h
func (_m *MessagingServiceMock) Subscribe(msgType string, h func(*messaging.Message)) {
	_m.Called(msgType, h)
}
