workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - checks
  - release

.setup: &setup |
  apt-get update
  apt-get -y install libsodium-dev
  tmpdir=$(mktemp -d)
  curl https://download.joinself.com/olm/libself-olm_0.1.14_amd64.deb -o ${tmpdir}/libself-olm_0.1.14_amd64.deb
  curl https://download.joinself.com/omemo/libself-omemo_0.1.1_amd64.deb -o ${tmpdir}/libself-omemo_0.1.1_amd64.deb
  apt-get -y install ${tmpdir}/libself-olm_0.1.14_amd64.deb
  apt-get -y install ${tmpdir}/libself-omemo_0.1.1_amd64.deb

before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

license-compliance:
  stage: checks
  image: licensefinder/license_finder
  script:
    - ${SCRIPTS_DIR}/license-check

secret-scan:
  stage: checks
  image:
    name: zricethezav/gitleaks:v8.2.4
    entrypoint: [""]
  script:
    - ${SCRIPTS_DIR}/git-secret-scan

unit-test:
  stage: checks
  image: golang:1.14.4-buster
  script:
    - *setup
    - go test -v ./...

release:
  stage: release
  image: eu.gcr.io/principal-oxide-204416/tools
  script:
    - ${SCRIPTS_DIR}/git-setup
    - version=$(${SCRIPTS_DIR}/git-new-version -n joinself)
    - ${SCRIPTS_DIR}/git-release -n joinself -v ${version}
    - ${SCRIPTS_DIR}/slack-release-notification -n joinself -v ${version}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
