// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MessagingClient is an autogenerated mock type for the messagingClient type
type MessagingClient struct {
	mock.Mock
}

// Command provides a mock function with given fields: command, selfID, payload
func (_m MessagingClient) Command(command string, selfID string, payload []byte) ([]byte, error) {
	ret := _m.Called(command, selfID, payload)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, []byte) []byte); ok {
		r0 = rf(command, selfID, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, []byte) error); ok {
		r1 = rf(command, selfID, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConnections provides a mock function with given fields:
func (_m MessagingClient) ListConnections() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Request provides a mock function with given fields: recipients, cid, data, timeout
func (_m MessagingClient) Request(recipients []string, cid, mtype string, priority int, data []byte, timeout time.Duration) (string, []byte, error) {
	ret := _m.Called(recipients, cid, data, timeout)

	var r0 string
	if rf, ok := ret.Get(0).(func([]string, string, []byte, time.Duration) string); ok {
		r0 = rf(recipients, cid, data, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 []byte
	if rf, ok := ret.Get(1).(func([]string, string, []byte, time.Duration) []byte); ok {
		r1 = rf(recipients, cid, data, timeout)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func([]string, string, []byte, time.Duration) error); ok {
		r2 = rf(recipients, cid, data, timeout)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Send provides a mock function with given fields: recipients, data
func (_m MessagingClient) Send(recipients []string, data []byte) error {
	ret := _m.Called(recipients, data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, []byte) error); ok {
		r0 = rf(recipients, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: msgType, sub
func (_m MessagingClient) Subscribe(msgType string, sub func(string, []byte)) {
	_m.Called(msgType, sub)
}
