// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// PkiClient is an autogenerated mock type for the pkiClient type
type PkiClient struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: selfID
func (_m *PkiClient) GetHistory(selfID string) ([]json.RawMessage, error) {
	ret := _m.Called(selfID)

	var r0 []json.RawMessage
	if rf, ok := ret.Get(0).(func(string) []json.RawMessage); ok {
		r0 = rf(selfID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]json.RawMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(selfID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
