name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  license-compliance:
    runs-on: ubuntu-latest
    container:
      image: joinself/license-finder:go
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: |
          exit 0
          apt-get update
          apt-get -y install libsodium-dev
          curl -Lo /tmp/olm.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -Lo /tmp/omemo.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/olm.deb /tmp/omemo.deb
      - name: License check
        run: |
          curl -Lo /tmp/dependency_decisions.yml https://static.joinself.com/license-finder/dependency_decisions.yml
          license_finder --decisions_file /tmp/dependency_decisions.yml
  secret-scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:v8.16.2
      options: "--user root"
    steps:
      - uses: actions/checkout@v3
      - name: Secrets check
        run: |
          exit 0
          chown root:root .
          wget -O /tmp/gitleaks.toml https://static.joinself.com/gitleaks/gitleaks.toml
          gitleaks -c /tmp/gitleaks.toml detect
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.2
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: |
          exit 0
          apt-get update
          apt-get -y install libsodium-dev
          curl -Lo /tmp/olm.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -Lo /tmp/omemo.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/olm.deb /tmp/omemo.deb
      - name: Test
        run: go test -v ./...
  publish:
    #if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    #needs: []
    container:
      image: joinself/tools
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - if: ${{ github.event_name == 'pull_request' }}
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Publish
        run: |
          chown root:root .
          # setup git
          git config --global user.name ci
          git config --global user.email ops@joinself.com

          # get new version
          branch=$(git branch --show-current)
          tags=$(git tag --merged ${branch} | sort -V)
          commit_message=$(git show -s --format=%s)
          if [[ "${tags}" == "" ]]; then
            version="0.1.0"
          else
            current_version=$(echo "${tags}" | tail -n 1)
            case $commit_message in
              *\[bump-major\]*)
                version=$(semver bump major $current_version)
                ;;
              *\[bump-patch\]*)
                version=$(semver bump patch $current_version)
                ;;
              *)
                version=$(semver bump minor $current_version)
                ;;
            esac
          fi

          env

          # create git tag
          git tag -a ${version} -m "${version}"
          git push origin ${version}

          # create github release
          #git_dir=${CI_WORKDIR}/.git
          subject=$(git log -n 1 --format=%s)
          body=$(git log -n 1 --format=%b | grep -E '^\*|^-' | sed 's/^*/-/g') || true
          if [[ -z ${body} ]]; then
            release_notes="- ${subject}"
          else
            release_notes="${body}"
          fi
          gh release create "${version}" --notes "${release_notes}"

          # slack release notification
