name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  license-compliance:
    uses: joinself/github-workflows-public/.github/workflows/license-compliance.yml@main
  secret-scan:
    uses: joinself/github-workflows-public/.github/workflows/secret-scan.yml@main
    with:
      continue-on-error: true
  test:
    needs: [license-compliance, secret-scan]
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.2-buster
      env:
        TESTSEC: ${{ secrets.TESTSEC }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        shell: bash
        run: |
          env
          echo "I am ${TESTSEC}"
          echo ${TESTSEC} > /tmp/foo
          cat /tmp/foo
          apt-get update
          apt-get -y install libsodium-dev
          curl -Lo /tmp/olm.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -Lo /tmp/omemo.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/olm.deb /tmp/omemo.deb
      - name: Test
        run: go test -v ./...
  publish:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    needs: test
    uses: joinself/github-workflows-public/.github/workflows/publish.yml@main

