name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.2-buster
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Test
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          apt-get update
          apt-get -y install libsodium-dev
          curl -Lo /tmp/olm.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -Lo /tmp/omemo.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/olm.deb /tmp/omemo.deb
          go test -v ./...
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
