name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted, linux-docker]
    container:
      image: golang:1.22.1-bookworm
    steps:
      - name: Setup job
        uses: joinself/github-actions/setup-job@main
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
      - name: Test
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env

          curl -L -H "Authorization: token ${GH_TOKEN}" -H 'Accept: application/octet-stream' --output self-sdk_0.10.0_amd64.deb https://api.github.com/repos/joinself/self-c-sdk/releases/assets/190141960
          apt install -y ./self-sdk_0.10.0_amd64.deb

          curl https://gotest-release.s3.amazonaws.com/gotest_linux > /usr/local/bin/gotest
          chmod +x /usr/local/bin/gotest

          cd account
          gotest -v
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
