name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.2-buster
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Test
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          curl -Lo /tmp/self-omemo.deb https://github.com/joinself/self-omemo/releases/download/0.4.0/self-omemo_0.4.0_amd64.deb
          dpkg -i /tmp/self-omemo.deb
          go test -v ./...
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
