name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.4-bookworm
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Test
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env

          mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://europe-apt.pkg.dev/doc/repo-signing-key.gpg | gpg --dearmor -o /etc/apt/keyrings/self.gpg
          echo "deb [signed-by=/etc/apt/keyrings/self.gpg] https://europe-apt.pkg.dev/projects/principal-oxide-204416 apt main" > /etc/apt/sources.list.d/self.list

          apt-get update && apt-get install -y self-sdk=0.85.0-14

          curl https://gotest-release.s3.amazonaws.com/gotest_linux > /usr/local/bin/gotest
          chmod +x /usr/local/bin/gotest

          cd account
          gotest -v

          echo "testing examples..."

          examples=(agreement chat connection credentials/issue credentials/request discovery)
          for e in ${examples[@]}; do
            cd ${CI_WORKDIR}/examples/${e} && go build -buildvcs=false .
          done
